// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChf062qImcQgs3APOex8NIOPL1YsrnArc',
    appId: '1:147574998932:web:1d5de6e91cb4f56336f181',
    messagingSenderId: '147574998932',
    projectId: 'foodscanner-b4ff4',
    authDomain: 'foodscanner-b4ff4.firebaseapp.com',
    storageBucket: 'foodscanner-b4ff4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDEZKOD5uexRF9qgKd5L3UfCmbiG_aU1Y',
    appId: '1:147574998932:android:b148c52399e2db6636f181',
    messagingSenderId: '147574998932',
    projectId: 'foodscanner-b4ff4',
    storageBucket: 'foodscanner-b4ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxmztfvKMKjX2ckO-0CJ55nfj2b8QDJAo',
    appId: '1:147574998932:ios:612b8a52986d3a5b36f181',
    messagingSenderId: '147574998932',
    projectId: 'foodscanner-b4ff4',
    storageBucket: 'foodscanner-b4ff4.firebasestorage.app',
    iosBundleId: 'com.example.hackton20252',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxmztfvKMKjX2ckO-0CJ55nfj2b8QDJAo',
    appId: '1:147574998932:ios:612b8a52986d3a5b36f181',
    messagingSenderId: '147574998932',
    projectId: 'foodscanner-b4ff4',
    storageBucket: 'foodscanner-b4ff4.firebasestorage.app',
    iosBundleId: 'com.example.hackton20252',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChf062qImcQgs3APOex8NIOPL1YsrnArc',
    appId: '1:147574998932:web:18d73edbf57cc81a36f181',
    messagingSenderId: '147574998932',
    projectId: 'foodscanner-b4ff4',
    authDomain: 'foodscanner-b4ff4.firebaseapp.com',
    storageBucket: 'foodscanner-b4ff4.firebasestorage.app',
  );
}
